### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by sebastianN01** [JoeyBallentine/Material-Map-Generator#3]
1 example
Traceback (most recent call last):
  File "H:\Git\Material-Map-Generator-1.3\generate.py", line 89, in <module>
    img = cv2.imread(path, cv2.cv2.IMREAD_COLOR)
AttributeError: module 'cv2' has no attribute 'cv2'
PS H:\Git\Material-Map-Generator-1.3>

**Comment by joeyballentine** [comment]
Get rid of that second cv2 in the cv2.cv2 on that line. No idea why that's there

**Comment by add-IV** [comment]
Got fixed with #2 but hasn't been released yet.

**Comment by sebastianN01** [comment]
thanks for help!
